# -*- mode: ruby -*-
# vi: set ft=ruby :




Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorU1 do |servidorU1|
    servidorU1.vm.box = "bento/ubuntu-20.04"
    servidorU1.vm.network :private_network, ip: "192.168.70.2"
    servidorU1.vm.provision "shell", path: "Scripts/Script_serverU1.sh"
    servidorU1.vm.hostname = "servidorU1"
  end

  config.vm.define :servidorU2 do |servidorU2|
    servidorU2.vm.box = "bento/ubuntu-20.04"
    servidorU2.vm.network :private_network, ip: "192.168.70.3"
    servidorU2.vm.provision "shell", path: "Scripts/Script_serverU2.sh"
    servidorU2.vm.hostname = "servidorU2"
  end


  config.vm.define :proxyServer do |proxyServer|
    proxyServer.vm.box = "bento/ubuntu-20.04"
    proxyServer.vm.network :private_network, ip: "192.168.70.4"
    proxyServer.vm.provision "shell", path: "Scripts/Script_proxy.sh"
    proxyServer.vm.hostname = "proxyServer"
  end



end




